### ISSUE TITLE
Stopped working in Firefox Nightly (10/10/2015).

### ISSUE THREAD

**Issue by joder666** [nmaier/about-addons-memory#21] opened 2015-10-10 18:01 UTC
Today i noticed that went i try "about:addons-memory" on a new tab i get:

>The address isn't valid
>The URL is not valid and cannot be loaded.
>
>    Web addresses are usually written like http://www.example.com/
>    Make sure that you're using forward slashes (i.e. /).

I install the addon in a clean profile, and tried "e10" on and off, it did not worked. 
Also i turned to false "xpinstall.signatures.required", no go.

It works ok on Firefox 41.01.

**Comment by Bugsbane** [comment] 2015-12-17 07:50
Getting this error on Firefox 43 on Ubuntu 15.10.

**Comment by reconrey** [comment] 2015-12-29 07:23
Getting this same error on FF 45.0a2 using Windows 10

**Comment by Smile4ever** [comment] 2015-12-29 13:05
@Bugsbane 
@reconrey
Make sure the about:config entry xpinstall.signatures.required is set to false or manually remove the addon and reinstall from here: https://addons.mozilla.org/firefox/addon/about-addons-memory/

**Comment by Smile4ever** [comment] 2015-12-29 13:31
I confirm about:addons-memory is no longer working in Firefox 46 (signed version used, no e10s).

**Comment by reconrey** [comment] 2015-12-29 16:45
@Smile4ever 
Setting xpinstall.signatures.required to false and removing/reinstalling the extension did not work

**Comment by Smile4ever** [comment] 2015-12-29 16:50
Okay then you are facing the same issue because your Firefox version >=45. We need the developer to look at this.

**Comment by reconrey** [comment] 2015-12-29 18:41
Intresting. I did a bit more testing on this using an Ubuntu 15.10 VM and I was able to get it to work on the 43.0 release channel, but once I updated to the beta channel, 44.0b4, it stopped working. So, perhaps this issue is related to it not being supported on non-release channels? It does seem odd that @Bugsbane was getting this issue with Firefox 43 using Ubuntu 15.10 and I am not however. Not sure if this project will get revived, but it has not been updated for over a year, so I'm not sure if we will get an official fix for this.

**Comment by Smile4ever** [comment] 2015-12-29 20:22
@Bugsbane is not facing this issue but rather the signature of the addon is missing.  The signature requirement was introduced in Firefox version 43.

**Comment by Bugsbane** [comment] 2016-01-09 23:21
> Make sure the about:config entry xpinstall.signatures.required is set to false or manually remove the addon and reinstall from here: https://addons.mozilla.org/firefox/addon/about-addons-memory/

Yes, I changed this, and it works fine for me now.

**Comment by reconrey** [comment] 2016-01-10 01:51
I just looked in to it again, and I noticed that replacing the loader.jsm with the one included in the ExtSDK's repo made navigating to about:addons-memory work, however, the page just indefinitely displays the loading screen. Also, navigating to chrome://about-addons-memory/content/about.xhtml with/without replacing the loader.jsm does the same as about:addons-memory, but does not work either. I'm not sure if this is specific to me, I have not tested on any other machines just yet, but it does not seem to be working. I will continue to look into this and keep you guys posted.

**Comment by jdorenbush** [comment] 2016-02-05 07:12
I tried setting xpinstall.signatures.required to false and reinstalling the add-on. Neither solution worked for me.

Firefox 44.0

**Comment by reconrey** [comment] 2016-02-05 18:51
@jdorenbush I believe the issue is with changes made in FF 44, there was a post made on the Firefox Addon Blog that addresses this. [https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/](https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/)

**Comment by tancrackers** [comment] 2016-02-15 15:56
I an on x64 Firefox 44.0.2 on Arch Linux, and the about:addons-memory page no longer works. It gives an error like when you use about:somethingnotthere

**Comment by edouard-lopez** [comment] 2016-02-17 17:15
@nmaier there is a pull request waiting to solve this issue. 
Could you update this thread when you review and merge it?

**Comment by InternalError503** [comment] 2016-02-18 01:26
@edouard-lopez 

You can simply use [github extension installer](https://addons.mozilla.org/en-US/firefox/addon/github-extension-installer) then browse the pull request [here](https://github.com/nmaier/about-addons-memory/tree/9c0f97d50200e4f5cda4a410e137e0326847927c) and install the working version.

__Do note:__ For firefox you will likely have to set `xpinstall.signatures.required` to `False` as the addon will be unsigned.

**Comment by edouard-lopez** [comment] 2016-02-18 09:36
@InternalError503 the extension just link to a `.zip`  file not an `.xpi`

**Comment by InternalError503** [comment] 2016-02-18 10:44
@edouard-lopez 

You need to **[install the addon](https://addons.mozilla.org/en-US/firefox/addon/github-extension-installer)** and _if you have the page open refresh it_ see the attached image.

![sbydbf287ybysbdfb](https://cloud.githubusercontent.com/assets/2867549/13140789/c6f875b0-d67f-11e5-99fc-673226deff30.jpg)

The button highlighted in red should appear.

**Comment by edouard-lopez** [comment] 2016-02-18 11:40
Seems [Google Translate Anywhere (Dictionary Anywhere) addon is problematic](http://add0n.com/dictionary.html).

**Comment by paulderdash** [comment] 2016-02-28 09:05
Tried installing with Github Extension installer. Installed but still does not work.

**Comment by wadkar** [comment] 2016-03-19 23:15
@InternalError503 thanks, I got it working.
@nmaier what can we do to help merge #23 ? Do we need some test or something?

**Comment by paulderdash** [comment] 2016-03-20 09:35
Wish I could get it working :(
Github Extension Installer tells me it installs after I 'Add to Firefox'. But there is still no addons:about-memory page, even after a FF restart..
@wadkar - was there anything else you did?
My FF memory usage has increased dramatically, trying to track down which add-on is causing this.
Unless it's due to switching from FF 32-bit to 64-bit version.

**Comment by wadkar** [comment] 2016-03-20 19:40
Sorry, nothing special besides installing the github extension installer, setting `xpinstall.signatures.required=false` in firefox and well, yeah thats it.

**Comment by Glimpf** [comment] 2016-03-27 13:55
Confirm what@wadkar said, github extension installer and downloading latest version did the job.
Beside the known about:config setting.

**Comment by Arthur-BDR** [comment] 2016-04-04 15:59
Hi, thanks for all the pointers.  I installed successfully the **github-extension-installer**, and then clicked on the 'Add To Firefox' button for the **nmaier/about-addons-memory** addon, and it was still spinning at 'Installing...' overnight on a top-configuration system of mine (tried that since it was also spinning on lower ones).

In an attempt for an alternative route, I'm able to click on 'Download' button next to it and get it, but it seems to be a source set and I'm not sure what it needs to compile and install (while pretty techie, I'm not a github guru). 

It seems to have worked for @Glimpf 8 days ago.  Though compared to @InternalError503 's Feb 18 post picture, the repository is different (e.g. it shows branch 'Tree: 9c...' and I'm seeing 'Branch: master', etc.)

My Firefox version is 45.0.1 (seems to be latest as of right now), and the system is running Windows 10 64-bit. (Which might also be different from the successful install above.)

**Any ideas what might be going wrong, or anything else I can try?**

Thanks.

**Comment by InternalError503** [comment] 2016-04-06 00:49
For people who are having difficulties reading, Following or understanding the following posts in this ticket by me sorry about that, See below for a simplified option.

#### Original posts:
https://github.com/nmaier/about-addons-memory/issues/21#issuecomment-185496731
https://github.com/nmaier/about-addons-memory/issues/21#issuecomment-185648782

**Here is the direct link to the test XPI file from [pull request](https://github.com/nmaier/about-addons-memory/pull/23)**

## [Download](https://github.com/InternalError503/about-addons-memory/raw/master/xpi/about-addons-memory.xpi)

**Comment by L0garithmic** [comment] 2016-04-06 19:38
Submitted the fixed XPI to Firefox, they accepted. Thanks InternalError503!
https://addons.mozilla.org/en-US/firefox/addon/about-addons-memory-2016/

**Comment by InternalError503** [comment] 2016-04-22 01:19
Updated the XPI build in my local repository to support Firefox 48.0 and lower.

See [comment](https://github.com/nmaier/about-addons-memory/issues/21#issuecomment-206054047) for more information.
See all changes made [here](https://github.com/InternalError503/about-addons-memory/compare/4d8bf08a8436e96941588014320e56cda761c2db...64231c1c8e76ce70b8e646ebe90e8486d251f17e)

## [Download](https://github.com/InternalError503/about-addons-memory/raw/master/xpi/about-addons-memory.xpi)

**Comment by paulderdash** [comment] 2016-04-22 08:50
@InternalError503 @L0garithmic - can this update be submitted to Firefox https://addons.mozilla.org/en-US/firefox/addon/about-addons-memory-2016/

**Comment by L0garithmic** [comment] 2016-04-28 20:57
Submitted it, waiting on review.

**Comment by InternalError503** [comment] 2016-05-08 15:05
Updated the XPI build in my local repository to support Firefox 49.0a1 and lower.

See [comment](https://github.com/nmaier/about-addons-memory/issues/21#issuecomment-206054047) for more information.
See all changes made [here](https://github.com/InternalError503/about-addons-memory/compare/64231c1c8e76ce70b8e646ebe90e8486d251f17e...34aa57a8ebde41849fb4050c62dcd81d5ba16c24)

### [Download](https://github.com/InternalError503/about-addons-memory/raw/master/xpi/about-addons-memory.xpi)

**Comment by InternalError503** [comment] 2016-05-17 00:31
Updated the XPI build in my local repository to support Firefox ` 29.0 - 49.0a1`

See [comment](https://github.com/nmaier/about-addons-memory/issues/21#issuecomment-206054047) for more information.
See all changes made [here](https://github.com/InternalError503/about-addons-memory/compare/64231c1c8e76ce70b8e646ebe90e8486d251f17e...ca24eedbc9821fac1eef6500206d280e8343c3a8)

### [Download](https://github.com/InternalError503/about-addons-memory/raw/master/xpi/about-addons-memory.xpi)

**Comment by InternalError503** [comment] 2016-05-17 05:05
Updated the XPI build in my local repository to support Firefox ` 29.0 - 49.0a1`

See **[comment](https://github.com/nmaier/about-addons-memory/issues/21#issuecomment-206054047)** for more information.
See all changes made **[here](https://github.com/InternalError503/about-addons-memory/compare/64231c1c8e76ce70b8e646ebe90e8486d251f17e...c7446732d693405f10a42384360869e6b4a6de58)**

**Fixed:** `Issue with being able to open multiple about:addons-memory tabs.`

### [Download](https://github.com/InternalError503/about-addons-memory/raw/master/xpi/about-addons-memory.xpi)

**Comment by InternalError503** [comment] 2016-05-17 11:58
Updated the XPI build in my local repository to support Firefox ` 24.0 - 49.0a1`

See **[comment](https://github.com/nmaier/about-addons-memory/issues/21#issuecomment-206054047)** for more information.
See all changes made **[here](https://github.com/InternalError503/about-addons-memory/compare/64231c1c8e76ce70b8e646ebe90e8486d251f17e...ecb52486239b200a56229518a52d7c65c504274e)**

**Now works with Firefox 24.0 and up.**
**_Note: Toolbar button only works from Firefox 29.0 and up._**

### [Download](https://github.com/InternalError503/about-addons-memory/raw/master/xpi/about-addons-memory.xpi)

**Comment by InternalError503** [comment] 2016-06-01 07:33
**Updated the XPI build in my local repository to support Firefox ` 24.0 - 49.0a1`**

**See [comment](https://github.com/nmaier/about-addons-memory/issues/21#issuecomment-206054047) for more information.**
 **See all changes made [here](https://github.com/InternalError503/about-addons-memory/compare/64231c1c8e76ce70b8e646ebe90e8486d251f17e...37558eac5d6ee54a94d81e77d4525bb14d3ca62d)**

**Now works with Firefox 24.0 and up.**
**_Note: Toolbar button only works from Firefox 29.0 and up._**

### [Download](https://github.com/InternalError503/about-addons-memory/raw/master/xpi/about-addons-memory.xpi)

@L0garithmic I see you have posted the builds to AMO, Please try this updated build and make sure to set the manifest support for the above 24.0 as minimum version.

**Comment by InternalError503** [comment] 2016-06-22 12:57
@L0garithmic Are you going to add the newer version of this with better compatibility [posted here](https://github.com/nmaier/about-addons-memory/issues/21#issuecomment-222915486) if not let me know and i will push it to AMO.

Thank you.

**Closed** 2016-08-12 07:41 UTC
