### ISSUE TITLE
Does not work with current release version.

### ISSUE THREAD

**Issue by Grossdm** [nmaier/about-addons-memory#24] opened 2016-03-27 04:02 UTC
I don't know which version of FF broke this extension, but it certainly does not work with v. 45.0.1.

**Comment by version365** [comment] 2016-03-27 09:08
Duplicate of #21

**Comment by L0garithmic** [comment] 2016-04-06 19:37
nmaier did not look like he planned on imp implementing the fixed version, so I posted my own
https://addons.mozilla.org/en-US/firefox/addon/about-addons-memory-2016/

**Comment by rayman89** [comment] 2016-07-29 01:51
@L0garithmic  your add-on does not display the page on firefox ESR 45.2.0 when I type the "url" the bar goes blank and nothing loads.

**Comment by InternalError503** [comment] 2016-07-29 04:35
@rayman89 

Does the build in [this comment](https://github.com/nmaier/about-addons-memory/issues/21#issuecomment-222915486) work as its compatible with Firefox 24 and up, Ive been waiting for @L0garithmic to update the AMO with the updated build.

**Comment by rayman89** [comment] 2016-07-29 21:19
@InternalError503 It does work. Thanks a lot.

**Closed** 2016-07-31 19:42 UTC
